TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += SIA-CavPlDrv.db

#=======================================
include $(TOP)/configure/RULES
