TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += LLRFLinPS.db
DB += LLRFSwPS.db
DB += SSASwPS.db

#=======================================
include $(TOP)/configure/RULES
