#!/usr/bin/python3
import re
import subprocess
from .templates import power, voltage, bi_2, adc, current, raw, bi
from .util import resistance

defaults = {
    "MIN": "-41.",
    "CTE": "1.",
    "DESC": "",
    "W": "PwrW",
    "dBm": "PwrdBm",
    "OFS": "OFSdB",
    "PREC": "2",
}

cal_sys_data = [
    {
        "ioc": "SIA-CalSys",
        "defaults": {
            "NAME": "$(P):RF-RFCalSys",
        },
        "readings": [
            {
                "ADC": "0",
                "CH": "0",
                "N": "1",
                "template": power,
                "p1": "25.695",
                "p2": "8.987",
                "p3": "-54.022",
                "p4": "25.999",
                "p5": "-4.632",
            },
            {
                "ADC": "0",
                "CH": "1",
                "N": "2",
                "template": power,
                "p1": "26.372",
                "p2": "7.434",
                "p3": "-52.123",
                "p4": "24.914",
                "p5": "-4.407",
            },
            {
                "ADC": "0",
                "CH": "2",
                "N": "3",
                "template": power,
                "p1": "25.288",
                "p2": "11.047",
                "p3": "-57.572",
                "p4": "28.544",
                "p5": "-5.273",
            },
            {
                "ADC": "0",
                "CH": "3",
                "N": "4",
                "template": power,
                "p1": "25.462",
                "p2": "9.837",
                "p3": "-55.759",
                "p4": "27.455",
                "p5": "-5.014",
            },
            {
                "ADC": "1",
                "CH": "0",
                "N": "5",
                "template": power,
                "p1": "27.04",
                "p2": "5.635",
                "p3": "-50.582",
                "p4": "24.352",
                "p5": "-4.349",
            },
            {
                "ADC": "1",
                "CH": "1",
                "N": "6",
                "template": power,
                "p1": "26.825",
                "p2": "4.895",
                "p3": "-48.644",
                "p4": "22.933",
                "p5": "-3.988",
            },
            {
                "ADC": "1",
                "CH": "2",
                "N": "7",
                "template": power,
                "p1": "30.582",
                "p2": "-6.623",
                "p3": "-34.136",
                "p4": "14.981",
                "p5": "-2.428",
            },
            {
                "ADC": "1",
                "CH": "3",
                "N": "8",
                "template": power,
                "p1": "24.146",
                "p2": "14.987",
                "p3": "-63.307",
                "p4": "31.503",
                "p5": "-5.777",
            },
            {
                "ADC": "2",
                "CH": "0",
                "N": "9",
                "template": power,
                "p1": "22.464",
                "p2": "19.31",
                "p3": "-65.795",
                "p4": "31.678",
                "p5": "-5.638",
            },
            {
                "ADC": "2",
                "CH": "1",
                "N": "10",
                "template": power,
                "p1": "22.953",
                "p2": "18.26",
                "p3": "-64.8",
                "p4": "31.063",
                "p5": "-5.462",
            },
            {
                "ADC": "2",
                "CH": "2",
                "N": "11",
                "template": power,
                "p1": "26.079",
                "p2": "6.869",
                "p3": "-51.077",
                "p4": "24.309",
                "p5": "-4.291",
            },
            {
                "ADC": "2",
                "CH": "3",
                "N": "12",
                "template": power,
                "p1": "26.898",
                "p2": "6.384",
                "p3": "-51.785",
                "p4": "25.116",
                "p5": "-4.544",
            },
            {
                "ADC": "3",
                "CH": "0",
                "N": "13",
                "template": power,
                "p1": "28.655",
                "p2": "-1.565",
                "p3": "-40.164",
                "p4": "17.855",
                "p5": "-2.887",
            },
            {
                "ADC": "3",
                "CH": "1",
                "N": "14",
                "template": power,
                "p1": "27.045",
                "p2": "5.212",
                "p3": "-50.12",
                "p4": "24.323",
                "p5": "-4.378",
            },
            {
                "ADC": "3",
                "CH": "2",
                "N": "15",
                "template": power,
                "p1": "23.962",
                "p2": "15.13",
                "p3": "-60.699",
                "p4": "28.789",
                "p5": "-5.006",
            },
            {
                "ADC": "3",
                "CH": "3",
                "N": "16",
                "template": power,
                "p1": "24.776",
                "p2": "12.062",
                "p3": "-57.845",
                "p4": "27.963",
                "p5": "-4.997",
            },
        ],
    },
    {
        "ioc": "BO-CalSys",
        "defaults": {
            "NAME": "$(P):RF-RFCalSys",
        },
        "readings": [
            {
                "ADC": "0",
                "CH": "0",
                "N": "1",
                "template": power,
                "p1": "27.028",
                "p2": "5.508",
                "p3": "-51.11",
                "p4": "24.832",
                "p5": "-4.439",
            },
            {
                "ADC": "0",
                "CH": "1",
                "N": "2",
                "template": power,
                "p1": "29.768",
                "p2": "-3.58",
                "p3": "-38.993",
                "p4": "17.851",
                "p5": "-2.993",
            },
            {
                "ADC": "0",
                "CH": "2",
                "N": "3",
                "template": power,
                "p1": "25.316",
                "p2": "10.44",
                "p3": "-56.912",
                "p4": "28.08",
                "p5": "-5.133",
            },
            {
                "ADC": "0",
                "CH": "3",
                "N": "4",
                "template": power,
                "p1": "31.929",
                "p2": "-8.979",
                "p3": "-33.803",
                "p4": "16.003",
                "p5": "-2.828",
            },
            {
                "ADC": "1",
                "CH": "0",
                "N": "5",
                "template": power,
                "p1": "24.599",
                "p2": "13.914",
                "p3": "-60.356",
                "p4": "29.486",
                "p5": "-5.342",
            },
            {
                "ADC": "1",
                "CH": "1",
                "N": "6",
                "template": power,
                "p1": "24.41",
                "p2": "14.764",
                "p3": "-61.678",
                "p4": "30.14",
                "p5": "-5.438",
            },
            {
                "ADC": "1",
                "CH": "2",
                "N": "7",
                "template": power,
                "p1": "26.592",
                "p2": "7.573",
                "p3": "-54.104",
                "p4": "26.822",
                "p5": "-4.94",
            },
            {
                "ADC": "1",
                "CH": "3",
                "N": "8",
                "template": power,
                "p1": "26.12",
                "p2": "7.477",
                "p3": "-51.271",
                "p4": "23.87",
                "p5": "-4.096",
            },
            {
                "ADC": "2",
                "CH": "0",
                "N": "9",
                "template": power,
                "p1": "24.921",
                "p2": "11.242",
                "p3": "-54.707",
                "p4": "-25.158",
                "p5": "-4.241",
            },
            {
                "ADC": "2",
                "CH": "1",
                "N": "10",
                "template": power,
                "p1": "28.116",
                "p2": "2.117",
                "p3": "-45.967",
                "p4": "21.71",
                "p5": "-3.806",
            },
            {
                "ADC": "2",
                "CH": "2",
                "N": "11",
                "template": power,
                "p1": "24.296",
                "p2": "14.477",
                "p3": "-60.429",
                "p4": "29.23",
                "p5": "-5.238",
            },
            {
                "ADC": "2",
                "CH": "3",
                "N": "12",
                "template": power,
                "p1": "22.995",
                "p2": "19.294",
                "p3": "-67.135",
                "p4": "32.896",
                "p5": "-5.952",
            },
            {
                "ADC": "3",
                "CH": "0",
                "N": "13",
                "template": power,
                "p1": "25.281",
                "p2": "11.254",
                "p3": "-57.028",
                "p4": "27.585",
                "p5": "-4.942",
            },
            {
                "ADC": "3",
                "CH": "1",
                "N": "14",
                "template": power,
                "p1": "27.848",
                "p2": "3.19",
                "p3": "-46.601",
                "p4": "21.971",
                "p5": "-3.833",
            },
            {
                "ADC": "3",
                "CH": "2",
                "N": "15",
                "template": power,
                "p1": "24.556",
                "p2": "12.71",
                "p3": "-58.544",
                "p4": "28.311",
                "p5": "-5.051",
            },
            {
                "ADC": "3",
                "CH": "3",
                "N": "16",
                "template": power,
                "p1": "21.661",
                "p2": "22.796",
                "p3": "-70.793",
                "p4": "34.488",
                "p5": "-6.175",
            },
        ],
    },
]


cav_pl_drv_data = {
    "ioc": "SIA-CavPlDrv",
    "readings": [
        {
            "ADC": "0",
            "CH": "0",
            "NAME": "RA-RaSIA01:RF-CavPlDrivers:VoltPos5V-Mon",
            "template": voltage,
            "CTE": "2.",
        },
        {
            "ADC": "0",
            "CH": "1",
            "NAME": "RA-RaSIA01:RF-CavPlDrivers:Current5V-Mon",
            "template": current,
        },
        {
            "ADC": "0",
            "CH": "2",
            "NAME": "RA-RaSIA01:RF-CavPlDrivers:VoltPos48V-Mon",
            "template": voltage,
            "CTE": resistance(90.9, 10.0),
        },
        {
            "ADC": "1",
            "CH": "0",
            "NAME": "RA-RaSIA01:RF-CavPlDrivers:Dr1Current-Mon",
            "template": current,
        },
        {
            "ADC": "1",
            "CH": "1",
            "NAME": "RA-RaSIA01:RF-CavPlDrivers:Dr1Enbl-Mon",
            "template": bi_2,
            "ZNAM": "Enable",
            "ONAM": "Disable",
        },
        {
            "ADC": "1",
            "CH": "2",
            "NAME": "RA-RaSIA01:RF-CavPlDrivers:Dr1Flt-Mon",
            "template": bi,
            "ZNAM": "Fail",
            "ONAM": "Normal",
        },
        {
            "ADC": "1",
            "CH": "3",
            "NAME": "SI-02SB:RF-P7Cav:Pl1Pos-Mon",
            "template": voltage,
        },
        {
            "ADC": "2",
            "CH": "0",
            "NAME": "RA-RaSIA01:RF-CavPlDrivers:Dr2Current-Mon",
            "template": current,
        },
        {
            "ADC": "2",
            "CH": "1",
            "NAME": "RA-RaSIA01:RF-CavPlDrivers:Dr2Enbl-Mon",
            "template": bi_2,
            "ZNAM": "Enable",
            "ONAM": "Disable",
        },
        {
            "ADC": "2",
            "CH": "2",
            "NAME": "RA-RaSIA01:RF-CavPlDrivers:Dr2Flt-Mon",
            "template": bi,
            "ZNAM": "Fail",
            "ONAM": "Normal",
        },
        {
            "ADC": "2",
            "CH": "3",
            "NAME": "SI-02SB:RF-P7Cav:Pl2Pos-Mon",
            "template": voltage,
        },
    ],
}


def write_data(directory: str, data: dict):
    filename = data["ioc"]
    db = ""
    with open("{}/{}.db".format(directory, filename), "w+") as f:
        _data_default = {} if "defaults" not in data else data["defaults"]

        db += adc.safe_substitute(defaults, ioc=data["ioc"], **_data_default)
        for reading in data["readings"]:
            db += reading["template"].safe_substitute(
                defaults, ioc=data["ioc"], **_data_default, **reading
            )
        f.write(db)
