TOP=../..
include $(TOP)/configure/CONFIG

DB += LLRFLinPS01.db
DB += LLRFLinPS02.db
DB += LLRFSwPS01.db
DB += LLRFSwPS02.db
DB += SSASwPS01.db
DB += SSASwPS02.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

