TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += SIA-CalSys.db
DB += SIA-CalSys.req

DB += BO-CalSys.db
DB += BO-CalSys.proto
DB += BO-CalSys.req
#=======================================
include $(TOP)/configure/RULES
