TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += SIA-CalSys.db
DB += SIA-CalSys.req

#=======================================
include $(TOP)/configure/RULES
